### ISSUE TITLE
Not reloading SLIM templates correctly

### ISSUE THREAD

**Issue by rennhak** [guard/guard-livereload#79]
I've successfully used Rack::Livereload and guard-livereload here with my Sinatra project. It reloads CSS/SASS/JS correctly, but does not so with my view templates (SLIM).

It notices that the SLIM files have changed and trigger a reload of the browser, but the content stays exactly the same.

Is this a bug or wrong-use issue?

**Comment by e2** [comment]
I'm closing this since the generated `Guardfile` has been changed recently: 

https://github.com/guard/guard-livereload/blob/master/lib/guard/livereload/templates/Guardfile

Depending on what you do, you may need a rule file.

Out of the box, slim files are supported for Rails applications. Otherwise, your SLIM file should be translated to a HTML file somewhere - and that HTML file is what Guard::LiveReload should be watching.

It's best to create a small repo showing the problem, because it may just be your setup.

**Comment by rennhak** [comment]
Thanks for following up on that, apologies for not responding much. Will give this a try once I can. Thanks again.
